# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Maven Build
        run: |
          cd my-app
          mvn versions:set -DnewVersion=1.0.${{ github.run_number }}
          mvn -B  clean package 
          mkdir artifact && cp target/*.jar artifact
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: my-app/artifact
          
      - uses: docker/login-action@v1.10.0
        with:
          username: jonyjalfon94
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Build Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: './my-app'
          file: '../Dockerfile'
          push: true
          tags: 'jonyjalfon94/my-app:1.0.${{ github.run_number }}'
#         run: |
#           cd my-app
#           docker build . -f ../Dockerfile -t jonyjalfon94/my-app:1.0.${{ github.run_number }}
          
      - name: Test Docker Image
        run: |
          docker run jonyjalfon94/my-app:1.0.${{ github.run_number }}


          
#       - name: Push Docker Image
#         run: |
#           docker push jonyjalfon94/my-app:1.0.${{ github.run_number }}
          

          
      

