name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest    # create ubuntu container 

    steps:
    - uses: actions/checkout@v2   # clone all repository file into the container
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: |
        mvn release:update-versions -B package --file my-app/pom.xml
        
    - name: Gather artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: maven-artifact
        path: target
        
