name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: clean
      run: mvn -B clean --file my-app/pom.xml
    
    - name: Build with Maven
      run: | 
        cd ./my-app
        mvn -B release:update-versions -f pom.xml
        tree
        echo "hello"
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_ACCESS_TOKEN }}
  
    - name: Build & Tag & Push docker image
      run: |
         docker image build -t michaaliev/hello_world:test . 
         docker push michaaliev/hello_world:test
  
    - name: update version in pom file
      run: |
          cd my-app
          git config --global user.name "Michaaliev"
          git config --global user.email "Michaaliev1663@gmail.com@gmail.com"
          git add pom.xml
          git commit -m "version update"
          git push
        
