
name: maven-hello-world

on:
  push:
    branches: [ updatejarversion ]
    paths: 'my-app/src/main/java/com/mycompany/app/**.java'
  #pull_request:
    #branches: [ updatejarversion ]

  workflow_dispatch:
env:
 JAR_VERSION : ''
 
jobs:
   #This job is builds Dockerfile, creates Docker Image, push it to DockerHub, downloading the Image and running it 
   Build_Push_Pull_Run_Docker_Artifact:
     #if: ${{ false }}
     #needs: [Build_and_Upload_Artifact]
     runs-on: ubuntu-latest
   
     steps:
     - uses: actions/checkout@v2
     
     - name: Update Jar version
       shell: pwsh
       run: | 
            $xmlFileName = "/home/runner/work/maven-hello-world/maven-hello-world/my-app/pom.xml"
            [xml]$xmlDoc = Get-Content $xmlFileName
            $currentVersion = ($xmlDoc.project.version).Split("-")
            $currentVersionSplited = $currentVersion.Split(".")
            $convertedToInt = [int]$currentVersionSplited[2]
            $convertedToInt+=1
            $newVersion = $currentVersionSplited[0]+"."+$currentVersionSplited[1]+"."+$convertedToInt+"-SNAPSHOT"
            echo $newVersion
            echo "::set-output name=JAR_VERSION::$newVersion"
            cd /home/runner/work/maven-hello-world/maven-hello-world/my-app
            mvn versions:set "-DnewVersion=$newVersion"
       id: update-jar-version-ps
     
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with: 
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
           
     - name: Build Docker
       run: |
        cd /home/runner/work/maven-hello-world/maven-hello-world/my-app
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:${{ steps.update-jar-version-ps.outputs.JAR_VERSION }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:${{ steps.update-jar-version-ps.outputs.JAR_VERSION }}

        
         
     - name: Pull and run Docker
       run: |
         docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:${{ steps.update-jar-version-ps.outputs.JAR_VERSION }}
         docker run -i --entrypoint "sh" ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:${{ steps.update-jar-version-ps.outputs.JAR_VERSION }} -c "java -cp my-app-${{ steps.update-jar-version-ps.outputs.JAR_VERSION }}.jar com.mycompany.app.App"
         
     - name: Commit and push changes
       run:
        git add /home/runner/work/maven-hello-world/maven-hello-world/my-app/pom.xml
