
name: maven-hello-world

on:
  push:
    branches: [ updatejarversion ]
    paths: 'my-app/src/main/java/com/mycompany/app/**.java'
  #pull_request:
    #branches: [ updatejarversion ]

  workflow_dispatch:
env:
 JAR_VERSION : ''
 
jobs:
   #This job is build the application and upload artifact to GitHub Repo 
   Build_and_Upload_Artifact:
    if: ${{ false }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Update Jar version
        shell: pwsh
        run: | 
            $xmlFileName = "${env:GITHUB_WORKSPACE}\my-app\pom.xml"
            [xml]$xmlDoc = Get-Content $xmlFileName
            $xmlDoc.project.version = "${env:JAR_VERSION}"
            $xmlDoc.Save("${env:GITHUB_WORKSPACE}\my-app\pom.xml")
            write-host "The version updated to " $xmlDoc.project.version
            
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
         java-version: '8'
         distribution: 'adopt'
         
      - name: Build with Maven
        working-directory: D:\a\maven-hello-world\maven-hello-world\my-app
        run: mvn package
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: maven-hello-world-artifact
          path: D:\a\maven-hello-world\maven-hello-world\my-app\target
          retention-days: 30
   
   #This job is builds Dockerfile, creates Docker Image, push it to DockerHub, downloading the Image and running it 
   Build_Push_Pull_Run_Docker_Artifact:
     #if: ${{ false }}
     #needs: [Build_and_Upload_Artifact]
     runs-on: ubuntu-latest
   
     steps:
     - uses: actions/checkout@v2
     
     - name: Update Jar version
       shell: pwsh
       run: | 
            $xmlFileName = "/home/runner/work/maven-hello-world/maven-hello-world/my-app/pom.xml"
            [xml]$xmlDoc = Get-Content $xmlFileName
            $currentVersion = ($xmlDoc.project.version).Split("-")
            $currentVersionSplited = $currentVersion.Split(".")
            $convertedToInt = [int]$currentVersionSplited[2]
            $convertedToInt+=1
            $newVersion = $currentVersionSplited[0]+"."+$currentVersionSplited[1]+"."+$convertedToInt+"-SNAPSHOT"
            echo $newVersion
            echo 'JAR_VERSION=$newVersion' | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
            cd /home/runner/work/maven-hello-world/maven-hello-world/my-app
            mvn versions:set "-DnewVersion=$newVersion"
     
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with: 
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
           
     - name: Build Docker
       run: |
        cd /home/runner/work/maven-hello-world/maven-hello-world/my-app
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:1.0.1-SNAPSHOT .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:1.0.1-SNAPSHOT

        
         
     - name: Pull and run Docker
       run: |
         docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:1.0.1-SNAPSHOT
         docker run ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-word:1.0.1-SNAPSHOT
