name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: clean
      run: mvn -B clean --file my-app/pom.xml
    
    - name: Checkout Latest Commit
      uses: actions/checkout@v2

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
    
    - name: Build with Maven
      run: | 
        pwd
        cd ./my-app
        pwd
        ls
        sed -n 7p pom.xml >> temp
        sed 's/[^0-9.]//g' temp >> version
        v=`cat version`
        v=`echo "${v%.*}.$((${v##*.}+1))"`
        echo $v
        mvn versions:set -DnewVersion=$v -B package --file pom.xml
        rm temp version
        tree
        pwd
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_ACCESS_TOKEN }}
  
    - name: Build & Tag & Push docker image
      run: |
         docker image build -t michaaliev/github:my-app . 
         docker push michaaliev/github:my-app
  
    - name: update file and push to remote
      run: |
          cd my-app
          git config --global user.name "Michaaliev"
          git config --global user.email "Michaaliev1663@gmail.com@gmail.com"
          git add pom.xml
          git commit -m "version update"
          git push
        
