
name: maven-hello-word

on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:
jobs:
  
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Update version
        shell: pwsh
        run: | 
            $xmlFileName = '$RUNNER_WORKSPACE/my-app/pom.xml'
            [xml]$xmlDoc = Get-Content $xmlFileName
            $xmlDoc.project.version = "1.0.1-SNAPSHOT"
            $xmlDoc.Save("$RUNNER_WORKSPACE/my-app/pom.xml")
            write-host $xmlDoc.project.version
            
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
         java-version: '8'
         distribution: 'adopt'
         
      - name: Build with Maven
        working-directory: "$RUNNER_WORKSPACE/my-app"
        run: mvn package
        
      - name: Copy Docker file
        shell: cmd
        run: xcopy "$RUNNER_WORKSPACE\my-app\Dockerfile" "$RUNNER_WORKSPACE\my-app\target"
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: maven-hello-word-artifact
          path: $RUNNER_WORKSPACE/my-app/target
          retention-days: 30
