# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: calc project CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: checkout main code
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Print Version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

    - name: build+Tag Docker Image
      run: |
         docker build -t calc .

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUBNAME }}
        password: ${{ secrets.DOCKERHUBPASS }}

    - name: Tag Dockerfile
      run: |
         docker tag calc ${{ secrets.DOCKERHUBNAME }}/calc:${{steps.bump.outputs.version}}
         docker images