name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: clean
      run: mvn -B clean --file my-app/pom.xml
    
    - name: Build with Maven
      run: | 
        cd ./my-app
        sed -n 7p pom.xml >> temp
        sed 's/[^0-9.]//g' temp >> version
        v=`cat version`
        v=`echo "${v%.*}.$((${v##*.}+1))"`
        echo $v
        mvn -B package --file my-app/pom.xml
        tree
        pwd
        
    - name: Build docker image with name
      run: docker image build -t michaaliev/github:my-app .  
        
